In [4]:
 import numpy as np

# Les constructeurs les plus important de Numpy pour le ML

In [5]:
A = np.array([1,2,3])
print(A.shape)

(3,)


In [6]:
B = np.zeros((3,2))
print(B.shape)
type(B.shape)

(3, 2)


tuple

In [7]:
C = np.ones((3,4))
C

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
D = np.full((2,3),9)
D

array([[9, 9, 9],
       [9, 9, 9]])

In [11]:
E = np.random.randn(3,4)
E # on a une serie de nombre dans le tableau issu de la ditribution normale centree reduite

array([[-0.27334078, -1.32109087,  1.21683325,  0.4594996 ],
       [-0.18356905, -0.17295541, -1.34069947, -0.20304837],
       [ 2.00009929, -0.15593406, -0.03718683, -0.10056077]])

In [12]:
F = np.eye(4)
F

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
G = np.linspace(0,10,20)
G

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [14]:
H = np.arange(0,10,0.5)
H

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

# Manipulation des tableaux

In [15]:
A = np.ones((3,2))
B = np.zeros((3,2))

In [19]:
# Concatenation horizontale
CH1 = np.hstack((A,B))
CH2 = np.concatenate((A,B),axis=0)
print(CH1)
print('')
print(CH2)

[[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [21]:
print(CH1.shape)
print(CH2.shape)

(3, 4)
(6, 2)


In [26]:
CH1.ravel()

array([1., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0.])

In [27]:
(CH1.ravel()).shape

(12,)

In [31]:
Z = (CH1.ravel()).reshape((CH1.ravel().shape[0],1))
print("Nouvelle dimension de Z:", Z.shape)
Z

Nouvelle dimension de Z: (12, 1)


array([[1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.]])

# Exercie

In [34]:
def initialisation(m,n):
    # m: nombre de lignes
    # n: nombre de colonnes
    # retourne une matrice aleatoire (m, n+1)
    # avec une colonne biais (remplie de "1") tout a droite
    X = np.random.randn(m,n)
    b = np.ones((X.shape[0],1))
    X = np.concatenate((X,b), axis=1)
    return X

In [35]:
initialisation(3,3)

array([[-0.72442331, -0.38169464, -1.47146648,  1.        ],
       [-0.26500179, -1.03170545,  0.29268809,  1.        ],
       [ 1.02640418, -1.24954806, -0.50271888,  1.        ]])