In [1]:
import numpy as np

In [2]:
np.random.seed(0)
A = np.random.randint(0,10,[2,3])
A

array([[5, 0, 3],
       [3, 7, 9]])

# Methodes ndarray

In [3]:
A.sum(axis=0)

array([ 8,  7, 12])

In [4]:
# A.prod(), A.cumsum(),A.argmin(), A.argmax()

# Statistique

In [5]:
A.mean() # moyenne
A.std() # ecart type
A.var() # variance

8.583333333333334

In [6]:
# Correleation coefficient: permet de tracer une matrice de correlation pour la matrice A
np.corrcoef(A)

array([[ 1.        , -0.56362148],
       [-0.56362148,  1.        ]])

In [7]:
# En machine learning, on aime souvent connaitre combien de fois un element se repete dans un tableau
np.unique(A,return_counts=True)
# Sa c'est une fonction tres utile; elle ressort deux tableaux: le premier contient tous les elements de la matrice et
# le deuxieme contient le nombre de fois que chaque element se repetre dans la matrice

(array([0, 3, 5, 7, 9]), array([1, 2, 1, 1, 1], dtype=int64))

In [8]:
B = np.random.randint(0,10,[5,5])
values, counts = np.unique(B, return_counts=True)

In [9]:
counts.argsort()

array([0, 1, 2, 4, 6, 9, 3, 5, 7, 8], dtype=int64)

In [10]:
values[counts.argsort()]

array([0, 1, 2, 4, 6, 9, 3, 5, 7, 8])

In [12]:
for i,j in zip(values[counts.argsort()], counts[counts.argsort()]):
    print(f'valeur {i} apparait {j}')

valeur 0 apparait 2
valeur 1 apparait 2
valeur 2 apparait 2
valeur 4 apparait 2
valeur 6 apparait 2
valeur 9 apparait 2
valeur 3 apparait 3
valeur 5 apparait 3
valeur 7 apparait 3
valeur 8 apparait 4


# NaN Corrections

In [14]:
# dans la realite, les dataset se presente sous la forme suivante
C = np.random.randn(5,5)
C[0,2] = np.nan
C[4,3] = np.nan
C

array([[ 1.41437719, -0.12405066,         nan,  0.22988654,  0.60489373],
       [ 1.62715982,  1.59456053,  0.23043417, -0.06491034, -0.96898025],
       [ 0.59124281, -0.7827755 , -0.44423283, -0.34518616, -0.88180055],
       [-0.44265324, -0.5409163 , -1.32322737, -0.11279892,  0.90734594],
       [ 0.81526991,  0.22909795, -1.02617878,         nan,  1.29269823]])

In [15]:
np.isnan(C)

array([[False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True, False]])

In [16]:
np.isnan(C).sum()

2

In [18]:
np.isnan(C).sum()/C.size

0.08

In [20]:
C[np.isnan(C)] = 0
C

array([[ 1.41437719, -0.12405066,  0.        ,  0.22988654,  0.60489373],
       [ 1.62715982,  1.59456053,  0.23043417, -0.06491034, -0.96898025],
       [ 0.59124281, -0.7827755 , -0.44423283, -0.34518616, -0.88180055],
       [-0.44265324, -0.5409163 , -1.32322737, -0.11279892,  0.90734594],
       [ 0.81526991,  0.22909795, -1.02617878,  0.        ,  1.29269823]])

# Algebre Lineaire

In [28]:
A = np.ones((2,3))
B = np.ones((3,2))
A

array([[1., 1., 1.],
       [1., 1., 1.]])

In [29]:
B

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [30]:
(A.T).shape

(3, 2)

In [31]:
A.dot(B)

array([[3., 3.],
       [3., 3.]])

In [32]:
B.dot(A)

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [34]:
# Determinant
A = np.random.randint(0,10, [3,3])
A

array([[3, 5, 9],
       [4, 4, 6],
       [4, 4, 3]])

In [35]:
# Calcul du determinant
np.linalg.det(A)

23.999999999999993

In [36]:
# Inverse d'une matrice
np.linalg.inv(A)

array([[-0.5       ,  0.875     , -0.25      ],
       [ 0.5       , -1.125     ,  0.75      ],
       [-0.        ,  0.33333333, -0.33333333]])

In [37]:
# Determination des valeurs et vecteurs propres d'une matrice
np.linalg.eig(A)

(array([13.58872344, -3.        , -0.58872344]),
 array([[-6.70561268e-01, -8.32050294e-01,  6.04408531e-01],
        [-5.73889829e-01,  1.85511715e-16, -7.73940635e-01],
        [-4.70104297e-01,  5.54700196e-01,  1.88960901e-01]]))

# Exercie
Standardizer la matrice A sur chaque colonne (chaque colonne doit avoir moyenne =0 et ecart type =1)

In [38]:
np.random.seed(0)
A = np.random.randint(0, 100, [10,5])
A

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72],
       [ 9, 20, 80, 69, 79],
       [47, 64, 82, 99, 88],
       [49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57],
       [32, 31, 74, 23, 35]])

In [40]:
means = A.mean(axis=0)
means

array([44.5, 47. , 60.5, 45.7, 64.5])

In [41]:
A = (A - A.mean(axis=0))/A.std(axis=0)
A

array([[-0.02206157,  0.        ,  0.13173823,  0.72539252,  0.10755798],
       [-1.56637126,  1.61579632, -1.48676006, -0.33034307,  0.96802178],
       [ 1.12513992,  1.84021247,  1.03508612, -1.14768676, -0.27965074],
       [ 0.90452425, -0.35906585,  0.99744662,  0.0102168 ,  1.01104497],
       [ 1.6104944 , -0.44883231, -1.33620208,  1.0659524 ,  0.32267393],
       [-1.56637126, -1.21184724,  0.73397016,  0.7935045 ,  0.62383626],
       [ 0.11030784,  0.76301493,  0.80924915,  1.81518411,  1.01104497],
       [ 0.1985541 , -0.80789816, -1.56203905, -0.90929485, -2.17267111],
       [-0.24267724, -0.67324847,  0.16937773, -1.24985473, -0.32267393],
       [-0.55153918, -0.7181317 ,  0.50813319, -0.77307091, -1.26918412]])